name: Release nightly

env:
  REPO_OWNER: ${{ vars.REPO_OWNER }}
  REPO_WEBSITE: ${{ vars.REPO_WEBSITE }}
  REPO_DESCRIPTION: ${{ vars.REPO_DESCRIPTION }}
  REPO_MAINTAINER: ${{ vars.REPO_MAINTAINER }}
  REPO_AUTHOR_NAME: ${{ vars.REPO_AUTHOR_NAME }}
  REPO_AUTHOR_EMAIL: ${{ vars.REPO_AUTHOR_EMAIL }}
  REPO_BINARY_NAME: ${{ vars.REPO_BINARY_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create_nightly_tag:
    name: Create nightly tag for master branch
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update nightly tag
        run: |
          git tag -d ${{ vars.NIGHTLY_TAG }} || true
          git push origin :refs/tags/${{ vars.NIGHTLY_TAG }} || true
          git tag ${{ vars.NIGHTLY_TAG }}
          git push origin ${{ vars.NIGHTLY_TAG }}

  release_nightly:
    needs: create_nightly_tag
    name: Release nightly version
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Delete existing nightly release
        run: |
          gh release delete nightly --yes || true

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: refs/tags/${{ vars.NIGHTLY_TAG }}
          name: Development build (master)
          body: |
            This build is directly sourced from the `master` branch in active development. As such, it may include experimental features and potential bugs.
          draft: false
          prerelease: true

      - name: Build assets with Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: ~> v2
          args: release --clean --snapshot

      - name: Upload assets to nightly release
        run: gh release upload ${{ vars.NIGHTLY_TAG }} dist/{*.tar.gz,*.zip,*.tar.zst,*.deb,*.rpm,*.apk,checksums.txt} --clobber

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: dist/checksums.txt
          if-no-files-found: error


  release_nightly_windows7:
    needs: release_nightly
    name: Release Windows 7 Nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.7
          check-latest: true

      - name: Build Windows 7 Binaries
        run: |
          go version
          rm go.mod go.sum
          go mod init github.com/ayoisaiah/f2/v2
          go mod tidy
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o f2.exe
          zip f2_master_windows7-amd64.zip f2.exe
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags '-extldflags "-static"' -o f2.exe
          zip f2_master_windows7-386.zip f2.exe

      - name: Download checksums
        uses: actions/download-artifact@v4
        with:
          name: checksums

      - name: Modify checksums
        run: |
          sha256sum f2_master_windows7-amd64.zip >> checksums.txt
          sha256sum f2_master_windows7-386.zip >> checksums.txt

      - name: Upload assets to nightly release
        run: gh release upload ${{ vars.NIGHTLY_TAG }} ./{*.zip,checksums.txt} --clobber
